### ISSUE TITLE
Great Project, License Question

### ISSUE THREAD

**Issue by ChristianOConnor** [MaximeHeckel/linear-vaporwave-react-three-fiber#2]
Hey @MaximeHeckel I love this project! I actually forked it here https://github.com/ChristianOConnor/linear-vaporwave-react-three-fiber-typescript. I added a custom layout with a daisyui tailwind css theme and components. I'm planning on improving the code of my fork and incorporating it into more projects as well. Could you consider making this project (https://github.com/MaximeHeckel/linear-vaporwave-react-three-fiber) MIT License so I can also make my fork MIT License?

**Comment by MaximeHeckel** [comment]
I can add a license

**Comment by ChristianOConnor** [comment]
Amazing thank you so much!
